server:
  port: 8080
spring:
  application:
    name: running-location-service
datasource:
  url: jdbc:mysql://localhost:3306/cs504
  username: root
  password: root
jpa:
  hibernate:
    ddl-auto: update